### ISSUE TITLE
Opdracht, presentatie & readme

### ISSUE THREAD

**Issue by KoopReynders** [Wesleyvd/Wesleyvd.github.io#1]
Wat ik mis in je Readme is een gestructureerde opbouw van je verhaal.
B.v. beginnen met wát de opdracht/demo is, welke hippe API je daarvoor gaat gebruiken/onderzoeken, en dan stap voor stap hoe je de PE hebt gedaan ...

Readme mist een duidelijk opbouw. Zie Moodle voor oplevercriteria.

**Comment by Wesleyvd** [comment]
Het meeste wat in deze de beoordelingscriteria stond had ik er al in zitten. Ik maak trouwens ook helemaal geen gebruik van een API, waardoor ik denk dat deze issue een copy-paste issue is. Ook heb ik uw feedback van de beoordeling meegenomen door bijvoorbeeld de toggle niet een + te laten zijn die draait naar een x, maar een ^ die naar beneden draait, aangezien dit beter voor de UX is.

**Comment by KoopReynders** [comment]
Check. 
je heb gelijk. Sticky Position is geen API. Maar een CSS feature !
