### ISSUE TITLE
Waar gebruik je de preIE* classes?

### ISSUE THREAD

**Issue by krijnhoetmer** [Wesleyvd/Wesleyvd.github.io#2]
Je voegt ze vast met een reden toe in je HTML :)

**Comment by Wesleyvd** [comment]
HA om eerlijk te zijn niet, had even snel een html skeleton geplukt van het magische internet :$ (http://htmlshell.com/)

**Comment by krijnhoetmer** [comment]
Probeer in code (en design) alleen toe te voegen wat je nodig hebt. Houdt de boel simpeler en veel makkelijker overdraagbaar aan anderen. In dit geval natuurlijk niet zo belangrijk, maar wel handig om hier vroeg mee te beginnen, voordat je jezelf de verkeerde patronen aanleert.

**Comment by KoopReynders** [comment]
done
