### ISSUE TITLE
Waarom mag ik niet zoomen?

### ISSUE THREAD

**Issue by krijnhoetmer** [Wesleyvd/Wesleyvd.github.io#3]
Is dit een bewuste keuze, of gekopieerde code?

**Comment by Wesleyvd** [comment]
Het verminderd click-delay (wanneer je bijvoorbeeld met dubble tap kan inzoomen) en nu wordt het click event meteen afgevuurd zonder 300ms delay voor een betere user experience:

https://www.youtube.com/watch?feature=player_embedded&v=DujfpXOKUp8#t=1435s

**Comment by krijnhoetmer** [comment]
Dat is een talk uit 2013. Is dit nog steeds relevant?

Probeer niet te snel af te gaan op verouderde informatie, maar hou er rekening mee dat het Web continu verbetert. En probeer dingen niet te kapot te maken voor een grote groep :)
