### ISSUE TITLE
Wat doen de horizontal--break hr's?

### ISSUE THREAD

**Issue by krijnhoetmer** [Wesleyvd/Wesleyvd.github.io#4]
Heb je deze echt nodig, of maakt de overige markup het al duidelijk genoeg?

**Comment by Wesleyvd** [comment]
Niet nodig eigenlijk, ik deed het voornamelijk zodat het wat overzichtelijker werd wanneer css/js het niet zou doen.

**Comment by krijnhoetmer** [comment]
Pas je ook je code aan bij het sluiten van issues?

Probeer in HTML semantisch te denken, niet visueel. Bij elke tag die je typt je afvragen: “wat betekent dit?”
