### ISSUE TITLE
Heading structuur kan beter

### ISSUE THREAD

**Issue by krijnhoetmer** [Wesleyvd/Wesleyvd.github.io#5]
Volgens mij ontbreekt er nog een niveau. Hou rekening met mensen die hiervan afhankelijk zijn.

**Comment by Wesleyvd** [comment]
Klopt! Ik had wel h1, h3, h4 maar geen h2. Ook had ik geen pagina titel, dus ik heb voor de duidelijkheid een h1 met magina titel nu (contact list). En eerst wasren de letters (A, B, etc) een h1, maar dat is natuurlijk ook helemaal niet correct semantisch gezien. Deze heb ik nu veranderd naar h2's.

**Comment by KoopReynders** [comment]
done
