### ISSUE TITLE
Verschil tussen alt en title

### ISSUE THREAD

**Issue by krijnhoetmer** [Wesleyvd/Wesleyvd.github.io#6]
Is 'Profile picture' een `alt` attribuut, of een `title`? Verplaats je in iemand die die afbeelding of foto niet kan zien. is het dan zinvol om daar 'Profile picture' te lezen/horen?

**Comment by Wesleyvd** [comment]
Het lijkt mij inderdaad eigenlijk onnodig als alt attribuut. Zo'n profielfoto is in dit geval puur decoratief en heeft verder geen toegevoegde waarde, dat is het inderdaad onnodig om te laten weten van 'hey, er is een foto van deze persoon', aangezien hij/zij het toch niet/nooit kan zien. Ook als iemand image blockers aan heeft maakt het verder niet uit voor de main content.

Ik vraag mij ook zeker af of een title per se nodig is. Alhoewel het dan wel gebruikt kan worden als tooltip.

"offers advisory information about the element for which it is set"  en "For instance, visual browsers frequently display the title as a "tool tip" (a short message that appears when the pointing device pauses over an object). Audio user agents may speak the title information in a similar context." (w3)

Hierdoor heb ik besloten om het alternative attribute te veranderen naar een title attribute

**Comment by KoopReynders** [comment]
done
