### ISSUE TITLE
Waar linkt <a href=""> heen?

### ISSUE THREAD

**Issue by krijnhoetmer** [Wesleyvd/Wesleyvd.github.io#7]
Stel dat je JavaScript breekt, uit staat, of wat dan ook; waar wil je dan dat die links heen gaan?

**Comment by Wesleyvd** [comment]
Die zouden dan moeten linken naar de <div class="details--small"> van dezelfde contactpersoon waar de gegevens van deze persoon staan

**Comment by krijnhoetmer** [comment]
Hoe bedoel je? (Voeg dit ook gewoon toe in je code ajb)
