### ISSUE TITLE
Mag een <h4> in een <ul>? :)

### ISSUE THREAD

**Issue by krijnhoetmer** [Wesleyvd/Wesleyvd.github.io#8]
Nee! Foei! Paniek! :D

**Comment by Wesleyvd** [comment]
Oops, heb ze buiten de unordered list gehaald nu! Als ik hem straks commit zitten ze er iig niet meer in!

**Comment by krijnhoetmer** [comment]
Committen maar! (Of issues pas sluiten als je het ook gecommit hebt)

**Comment by KoopReynders** [comment]
done
