### ISSUE TITLE
Wat als een browser `classList` niet ondersteunt?

### ISSUE THREAD

**Issue by krijnhoetmer** [Wesleyvd/Wesleyvd.github.io#9]
Of `querySelectorAll`, of `addEventListener`. Wat gebeurt er bijvoorbeeld in IE9 in de console?

**Comment by Wesleyvd** [comment]
Wat ik nu doe is standaard alles laten zien en dan de contact details hiden met JS, indien `querySelectorAll ` niet gevonden wordt, dan worden de details dus ook niet verborgen en blijven dus gewoon zichtbaar en bruikbaar. Ik heb dit getest met internet explorer en door oudere versies te emuleren

**Comment by krijnhoetmer** [comment]
En je krijgt geen fout in je error console?

**Comment by Wesleyvd** [comment]
wel een error dat het undefined is, maar het enige wat er dan gebeurd is dat de elementen niet verborgen worden met JS, de website werkt gewoon volledig (ongeveer hetzelfde effect als wanneer JS helemaal uit staat)

**Comment by krijnhoetmer** [comment]
Dat begrijp ik, in dit geval blijkbaar niet zo'n probleem. Maar probeer jezelf aan te leren om zo te coden dat je geen (onverwachte) fouten krijgt. Hoe zou je dat in dit geval doen?

**Comment by Wesleyvd** [comment]
Dan zou ik denk ik Classname gebruiken

**Comment by Wesleyvd** [comment]
Ipv classlist bedoel ik

**Comment by Wesleyvd** [comment]
Maar je kan Classname eventueel ook gebruiken als queryselectorall.

if(element.className === "something") {
          //do something 
          goNextElement();
}

**Comment by KoopReynders** [comment]
done

**Comment by krijnhoetmer** [comment]
Ik doelde meer op feature detection.
